# Generated by Django 4.1 on 2022-08-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_test_year_in_school'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('AT', 'antique'), ('SC', 'starCard'), ('PT', 'painting'), ('CN', 'coin'), ('BG', 'bag'), ('SE', 'shoes'), ('AH', 'autograph'), ('SR', 'souvenir'), ('OS', 'others')], default='OS', max_length=2),
        ),
    ]
