# Generated by Django 4.1 on 2022-09-15 13:11

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_picture_descriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to=user.models.rename_pic),
        ),
    ]
